import { Header } from "@/components/layout/header";
import "../../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Footer } from "@/components/layout/footer";
import { Banner } from "@/components/ui/banner";
import { Provider } from "@/helper/frontend/state/globalContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className + " text-sm text-secondary"}>
        <Provider>
          <Header />
          {children}
          <Banner
            title="Shop Faster With Groceyish App"
            description="Available on both IOS & Android"
            // url="/img/home-banner-1.png"
            // bgColor="#FFD480"
          />
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
